// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzwmjdhyomdampdigagy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6d21qZGh5b21kYW1wZGlnYWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3MjEzMDAsImV4cCI6MjA5MTI5NzMwMH0.aLgZK4kvn8OYHkBRIUlrTcYpfRx2fbcFR_hkmbgu28w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});